import { Signika } from "next/font/google";
import "./globals.css";

const signika = Signika({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-signika'
})

export const metadata = {
  title: "Terra Segara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${signika.className} w-screen block mx-auto bg-gradient-to-b from-white to-white overflow-x-hidden`}>
          {children}
        <p className="absolute bottom-2 w-full text-secondary text-center">Simplex Creative Agency</p>
      </body>
    </html>
  );
}
