import { Signika } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer";

const signika = Signika({
  subsets: ['latin'],
  weight:'variable',
  display: 'swap',
  variable: '--font-signika'
})

export const metadata = {
  title: "Terra Segara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Logo Initial (two tone).ico" sizes="any" />
      </head>
      <body className={`${signika.className} sm:max-w-5xl max-w-sm flex flex-col items-center mx-auto bg-gradient-to-b from-white to-white overflow-x-hidden`}>
          <Navbar />
          {children}
          <footer>
            <Footer />
          </footer>
      </body>
    </html>
  );
}
